baseURL = 'https://tacedata.ca/'
languageCode = 'en-us'

theme = 'PaperMod'

title = 'TACE Data'
copyright = '© 2026 TACE Data Management Inc.'

[params]
  author = "Scott LeBlanc"

[params.profileMode]
  enabled  = true
  title    = "Scott LeBlanc"
  subtitle = "Oracle DBA / AI Enthusiast / AWS Tinkerer / PowerShell Automator"
  imageUrl = "tace.logo.png"
  imageWidth  = 80
  imageHeight = 80

[[params.profileMode.buttons]]
  name = "Projects"
  url  = "/projects/"

[[params.profileMode.buttons]]
  name = "Blog"
  url  = "/posts/"

[[params.socialIcons]]
  name = "github"
  url  = "https://github.com/scottyleblanc"

[[params.socialIcons]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/leblancscott/"

[params.label]
  text = "TACE Data Management Inc"
  icon = "tace.logo.png"
  iconHeight = 35

[markup.goldmark.renderer]
  unsafe = true
