[[main]]
name   = "Projects"
url    = "/projects/"
weight = 10

[[main]]
name   = "Blog"
url    = "/posts/"
weight = 20

[[main]]
name   = "Contact"
url    = "/contact/"
weight = 30

[[main]]
name   = "About"
url    = "/about/"
weight = 40


