[[main]]
name   = "projects"
url    = "/projects/"
weight = 10

[[main]]
name   = "blog"
url    = "/posts/"
weight = 20

[[main]]
name   = "contact"
url    = "/contact/"
weight = 30

[[main]]
name   = "about"
url    = "/about/"
weight = 40
