[[main]]
name   = "portfolio"
url    = "/portfolio/"
weight = 5

[[main]]
name   = "projects"
url    = "/projects/"
weight = 10

[[main]]
name   = "blog"
url    = "/posts/"
weight = 20

[[main]]
name   = "contact"
url    = "/contact/"
weight = 40

[[main]]
name   = "about"
url    = "/about/"
weight = 50
