baseURL = 'https://REDACTED_CF_DOMAIN/'
languageCode = 'en-us'
title = 'tacedata'
theme = 'PaperMod'

[params]
  author = "Scott LeBlanc"

[params.label]
  text = "TACE DATA"
  icon = "/logo.png"
  iconHeight = 35

[markup.goldmark.renderer]
  unsafe = true
